### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by elliotwoods** [roymacdonald/ofxSoundObjects#11]
I can't see any mention of portaudio in this repo which is required for libaudiodecoder to work on windows
i'm trying to get everything built right, but since libaudiodecoder hasn't been updated for 4 years..that's a bit tricky

**Comment by elliotwoods** [comment]
i'm wondering if you have an example working on windows, ideally windows 10 / vs2015 / x64 / oF 0.9.0

**Comment by roymacdonald** [comment]
Hi @elliotwoods I don't. I remember that it worked for me on windows some time ago. Let me look around and I'll ping you when I have it. best!

**Comment by elliotwoods** [comment]
Hey!
I figured out a way to get libaudiodecoder working
It completely flies in the face of the instructions :), but it just about
works now
Really horrible to work with actually :(

**Comment by roymacdonald** [comment]
@elliotwoods  can you pr that please ?

**Comment by elliotwoods** [comment]
ahk.. I hope you don't hate me for this.
I looked at ofxSoundObjects first, but realised I only needed the sound decoder
so I went with https://github.com/kylemcdonald/ofxAudioDecoder/pull/3

**Comment by roymacdonald** [comment]
@elliotwoods lol. no need to hate you. :)
Actually that PR is really helpful.
Take care.
