### ISSUE TITLE
weird sound artefact when using setSpeed in soundPlayerObject

### ISSUE THREAD

**Issue by gllmAR** [roymacdonald/ofxSoundObjects#16]
in `example-soundPlayerObject`, added a speed parameter.
 
![screen shot 2017-08-09 at 12 43 30](https://user-images.githubusercontent.com/7544151/29133123-758f4720-7d00-11e7-8db4-55ab89d202b5.png)

when setting any value beside 1 sound is completely destroy (strange feedback hard to explain in word).

* speed at 1, sound OK
![screen shot 2017-08-09 at 12 40 01](https://user-images.githubusercontent.com/7544151/29132991-043dcfd8-7d00-11e7-865d-13dc489345a9.png)
* speed at 1.001, sound is broken
![screen shot 2017-08-09 at 12 40 22](https://user-images.githubusercontent.com/7544151/29132992-044ee8ea-7d00-11e7-846f-c203cc2117ca.png)

using of_v20170714_osx_release -> osx 10.11.6
(awesome addon by the way.)

**Comment by roymacdonald** [comment]
Hi, I've seen that too.
I have a working version with a lot of improvements and fixes, but haven't published yet because it is untested on all platforms and I made several changes to its "api". I could upload it as some kind of experimental release. I'll try to make such later today or tomorrow.
best

**Comment by gllmAR** [comment]
Looking forward to test this experimental release.
Got a OSX, a linux64(archlinux) and a armv7 on hand. 
Would be my pleasure to report for these platform.
Cheers.

**Comment by dfeeuh** [comment]
Hi Roy

Any more progress on this? It looks like the resampledBuffer is getting trashed on each change. 
I also tested this with a 1s sine wave and discovered that without looping it outputs a constant buzz at the end, suggesting the buffer hasn't properly cleared. 
David

**Comment by roymacdonald** [comment]
Hi @dfeeuh 
I have indeed. but I've made a lot of changes to the whole addon so I'll push it as a experimental branch as I havent tested it thoroughly. I'll push later today. I'll let you know.
best

**Comment by roymacdonald** [comment]
Hi @dfeeuh I just pushed several changes and improovements to the master repo, along with a fix for this issue.
cheers
