### ISSUE TITLE
SineWaveGenerator.h bug

### ISSUE THREAD

**Issue by dfeeuh** [roymacdonald/ofxSoundObjects#17]
[SineWaveGenerator.patch.txt](https://github.com/roymacdonald/ofxSoundObjects/files/1489120/SineWaveGenerator.patch.txt)

Hi there, your method for generating a sine wave has a bug in it that causes it to sound distorted in the example-audioOutput. The currentPhase isn't correctly updated. I've attached a patch with a fix (there's no need for the separate 'phase' member).

**Comment by roymacdonald** [comment]
Thanks.
Can you please make a Pull request with the changes?
best regards

**Comment by roymacdonald** [comment]
Fixed in https://github.com/roymacdonald/ofxSoundObjects/pull/19
