### ISSUE TITLE
ofxBasicSoundPlayer compiling errors

### ISSUE THREAD

**Issue by dfeeuh** [roymacdonald/ofxSoundObjects#18]
Hi

ofxBasicSoundPlayer.h requires override keyword on virtual functions.
Patch attached:

[ofxBasicSoundPlayer.patch.txt](https://github.com/roymacdonald/ofxSoundObjects/files/1489131/ofxBasicSoundPlayer.patch.txt)

**Comment by roymacdonald** [comment]
Hi, Thanks.
well the use of override is not really mandatory but certainly would help.
Can you please make a pull request rather tan attaching the patch file. It's better house keeping I think.
best

**Comment by dfeeuh** [comment]
Thanks Roy

It looks like it’s mandatory on clang (Mac OS). I tried to create a branch and push it but it looks like I don’t have permission:

Username for 'https://github.com': dfeeuh
Password for 'https://dfeeuh@github.com':
remote: Permission to roymacdonald/ofxSoundObjects.git denied to dfeeuh.
fatal: unable to access 'https://github.com/roymacdonald/ofxSoundObjects.git/': The requested URL returned error: 403

David

**Comment by roymacdonald** [comment]
Hi! Well then even better adding this.
You cannot push directly to my repo. Yo have to fork my repo, which will create a copy of my repo in your account, which we call fork. then push to your fork and create a pull request from there. If you can't manage to achieve this,let me know and I'll add those patches.
thnks

**Comment by roymacdonald** [comment]
closed by PR https://github.com/roymacdonald/ofxSoundObjects/pull/19
