### ISSUE TITLE
missing libaudiodecoder

### ISSUE THREAD

**Issue by thomasgeissl** [roymacdonald/ofxSoundObjects#2]
Can we include libaudiodecoder?
Removing the .git folder inside libaudiodecoder should fix this.
Or at least add a note to the readme file.

**Comment by roymacdonald** [comment]
Hi, it is already included. what do you mean?

**Comment by roymacdonald** [comment]
Now that I see your commit I get it. Can you PR please?

**Comment by thomasgeissl** [comment]
I already did that: https://github.com/roymacdonald/ofxSoundObjects/pull/9
