### ISSUE TITLE
Resampling with looping crash

### ISSUE THREAD

**Issue by dfeeuh** [roymacdonald/ofxSoundObjects#20]
Hi Roy, thanks for the latest update. 
I wanted to try looping this and notice I have to add setLoop(true) after calling play() in the soundPlayerObject example. 
I tested it with a 1s 440Hz tone and noticed there was quite a lot of clicking on each loop.
Tested it with a 10s 440Hz tone, no clicking but when dragging the speed slider back and forth it always crashes at the same place. I've attached my XCode screen grab.
Thanks again
David
![screen shot 2017-11-28 at 11 40 16](https://user-images.githubusercontent.com/32520630/33318002-f37cc464-d430-11e7-8049-047a1f8453b7.png)

**Comment by roymacdonald** [comment]
Which OF version are you using? does this happen with the newest nightly build? You can find nightly builds in http://openframeworks.cc/download/ towards the end of the page

**Comment by dfeeuh** [comment]
Hi Roy, just got the latest nightly there (was using 0.9.8) and I get the same issue in the same way.

**Comment by roymacdonald** [comment]
Hi,
The problem has to do with ofSoundBuffer. I made a fix to it related to a different  issue https://github.com/roymacdonald/ofxSoundObjects/issues/16 which is already merged to the openframeworks master branch. You'll need to download openframeworks from github master. There are a few more steps you'll need to do to make OF compile, but theres a readme for that.

As for the clicking while the loop happens that is probably because the audio file itself starts with a sample value too different from the ending value. What the sound player does for looping is simply when the file samples en it will inmediatelly attach the samples from the begining of the file. There's no kind of smoothing o interpolation.

Let me know how if you make it work.
BTW how many channels does your file has?

**Comment by dfeeuh** [comment]
[Archive.zip](https://github.com/roymacdonald/ofxSoundObjects/files/1532393/Archive.zip)
Hi Roy
I've been looking at this for a few days now. I got the latest repo of the ofSoundBuffer but it does look to be a bug in it. I'm really surprised it hasn't been spotted before as it always happens eventually when running anything that uses resampling. The handling for looping isn't correct as it needs 'position' to be returned to the beginning if it approaches the end of the buffer, this isn't handled. The current implementation is pretty inefficient as the only way to fix it is to test on every single iteration of the final stage of the loop. 
The other thing that happens is resBufferPtr is increment in the inner loop and the outer loop, so that's probably the source of the click I could hear. I've modelled it up in matlab (freemat will work). However, I think it should be possible to algebraically work out the loop length rather than testing in the loop each time.
I've attached the script I wrote to analyse it. Unfortunately I don't have the bandwidth fix it myself but hope this is of help.
Best 
David

**Comment by roymacdonald** [comment]
Hi David,
yeah, I agree that it is quite inefficient and buggy. I didn't write ofSoundBuffer. I just made that quick fix so it could get merged fast, any bigger change would require a review, thus time.
I know that it could be done in a much more efficient and less buggy way, I'll try take a look at it.
I even dont like the algorithm itself.
I'll take a look at what you sent although I don't know mathlab. 
I'll let you know if I have make any improvement.
Best!

**Comment by dfeeuh** [comment]
Hi Roy
I've been tinkering with this for a few weeks and managed to rewrite the ofSoundBuffer linearResample function in a much more reliable way. Unfortunately I can't seem to properly test it on the master branch of openframeworks, it seems to be massively different to the stable one. 
I could send you my changes here and you're welcome to integrate them or maybe you know a quick way to get master working. 
Thanks
David

**Comment by roymacdonald** [comment]
Hi David, that's great. I develop against the master branch, and I know that ofSoundBuffer has a lot of differences with the oficial release.
Just post the resampling function here and I'll see how to add it.
thanks

**Comment by dfeeuh** [comment]
Thanks Roy, would be great to see this incorporated. I may even look at the other resampling function. Developed using Test-Driven Development as well as testing as above and looping a sinusoid then dragging the speed slider. You shouldn't hear any clicks at all. 

[ofSoundBuffer_cpp.zip](https://github.com/roymacdonald/ofxSoundObjects/files/1582635/ofSoundBuffer_cpp.zip)

**Comment by roymacdonald** [comment]
Hi, great! I'll let you know how it goes.
best!

**Comment by roymacdonald** [comment]
hey @dfeeuh I tried out your algorithm and it indeed loops correctly buy the interpolation part is wrong and it gives some nasty results. It has to do with the float position and intPosition used for the interpolation. It should be frame based and you are using it sample based.
<img width="1024" alt="screen shot 2018-01-03 at 11 45 58" src="https://user-images.githubusercontent.com/974878/34524835-b7928ba2-f07b-11e7-95f9-e967d7a2acc3.png">
The upper two waves are the original, the middle two are the resampled ones with the current algo, and the two at the bottom are using your algo.

**Comment by dfeeuh** [comment]
You're quite right! I realised after sending it I'd only tested it in mono. 
Some whacky sounds though...
I'll try and debug soon and I'll have a look at the lib aswell.
David

**Comment by dfeeuh** [comment]
Hi Roy, please find attached debugged and tested for stereo and mono.
David

[ofSoundBuffer.cpp.zip](https://github.com/roymacdonald/ofxSoundObjects/files/1616255/ofSoundBuffer.cpp.zip)

**Comment by roymacdonald** [comment]
Hi David,
thanks! I'll take a look at it during the weekend. Now I'm super busy.
cheers

**Comment by roymacdonald** [comment]
Hi David,
I can not really recall what happened. I know that some fixings have been done to the ofSoundBuffer, but I think that the most straight forwards way would be to open an Issue and a pull request in openFrameworks' repo. I will take a look at what you've attached anyways.
Cheers

**Comment by dfeeuh** [comment]
OK, i'm not really familiar with working with github but I'll try that.

**Comment by roymacdonald** [comment]
you might want to take a look at this https://github.com/openframeworks/openFrameworks/wiki/openFrameworks-git-workflow
let me know if you need any git help.
cheers
