### ISSUE TITLE
[soundPlayerObject] if speed != 1 on a stereo source only left channel output

### ISSUE THREAD

**Issue by gllmAR** [roymacdonald/ofxSoundObjects#21]
to reproduce; load a stereo source, change speed to anything beside 1 

For instance, I used a this alternating 440 hz tone @-18db   [stereo-test.wav.zip](https://github.com/roymacdonald/ofxSoundObjects/files/1516276/stereo-test.wav.zip)

observation:

when changing the speed settings, the player discard the second channel and seem's to add distortion on the whole output channel. When speed is dial back at 1, everything goes back to normal.

![artboard 1](https://user-images.githubusercontent.com/7544151/33411087-8339d508-d551-11e7-9757-1b3f4aa4ceb7.png)

same problem happen in this alternative sound player. Don't know if it is related.
https://github.com/arturoc/ofxBasicSoundPlayer

  (big thanks for the recent updates on that addon)

**Comment by roymacdonald** [comment]
Hi, which openFrameworks version are you using? I think that there is a problem in the resampling algorithm in the ofSoundBuffer that got fixed recenlty. try out the nightly builds that are available at the end of the following page 
openframeworks.io/downloads

please let me know how it goes!

**Comment by gllmAR** [comment]
I'm  using of_v20170714_osx_nightly on osx 10.11. 
seem's to be still the most recent nightly build. 

Do you have a different behaviour on your setup?

**Comment by roymacdonald** [comment]
im not getting distortion, at least I'm not hearing any, but the channels discarding happens. I'll check whats going on.

**Comment by roymacdonald** [comment]
thanks for noticing this

**Comment by gllmAR** [comment]
genius. ! Thanks!
