### ISSUE TITLE
can't play audio files?

### ISSUE THREAD

**Issue by jaysonh** [roymacdonald/ofxSoundObjects#22]
Trying to simply play an audio file with this code:

`if(player.load(ofToDataPath("g.wav")))
    {
    
        stream.setup(2, 0, player.getSoundFile().getSampleRate(), 256, 1);
        stream.setOutput(output);
        
        player.play();
        
        wave.setup(0, 0, ofGetWidth(), ofGetHeight());
        
        player.connectTo(wave).connectTo(output);
    }else
    {
        cout << "cannot load audio file"<<endl;
    }`

But I get error messages:
2018-01-26 08:58:47.812284+0000 MarijaLaserVidSyncDebug[5812:251837] [AudioHAL_Client] HALC_ShellObject.cpp:517:SetPropertyData:  HALC_ShellObject::SetPropertyData: call to the proxy failed, Error: 560226676 (!dat)
2018-01-26 08:58:47.812311+0000 MarijaLaserVidSyncDebug[5812:251837] [AudioHAL_Client] HALPlugIn.cpp:325:ObjectSetPropertyData:  HALPlugIn::ObjectSetPropertyData: got an error from the plug-in routine, Error: 560226676 (!dat)
[ error ] RtApiCore::probeDeviceOpen: system error (kAudioDeviceUnsupportedFormatError) setting sample rate for device (1).

I've tried various wav and mp3 audio files and always get the same error.

**Comment by roymacdonald** [comment]
Hi, that looks like something with the hardware abstraction layer.
Some things to try first. Are you able to run the audioInput or audioOutput examples from openFrameworks? This addon builds on top of OF's audio implmentation, which is the one dealing with hardware (through another third-party library).
Are you using an audio interface? if so, do you get the same problem with the integrated sound device?
the error mentions sample rate problems. did you try using files with other sample rates? manually match the sample rate of your sound device with the file you are trying to play.

**Comment by jaysonh** [comment]
Ok I found the problem, the addon doesn't seem to like mp3 or wav files with 22050 sample rate.
