### ISSUE TITLE
using ofxSoundFile increases bit depth from 16 bits to 32 bits

### ISSUE THREAD

**Issue by anaelisa24** [roymacdonald/ofxSoundObjects#23]
Hi,

So I've been trying to use ofxSoundFile to read audio files and manipulate them later with ofxFft. However I'm having issues with the object that I get when I load the audio. I'm trying to load a 16-bit, mono, 44.1 kHz sound file and I'm getting a 32-bit, stereo, 44.1 kHz ofxSoundFile object. So essentially I get an array that's 4 times longer that what I need. I also tried reading a file that's 24 bits, stereo and I get the same issue. I get a 32-bit, stereo object. So the stereo/mono I can easily fix by just taking every other sample. But I need to also get rid of half the samples gotten by the bit depth increase.

Thanks in advance for the help

**Comment by roymacdonald** [comment]
Hi, you should try [ofxAudioFile](https://github.com/npisanti/ofxAudioFile). I am going to switch this addon to use  ofxAudioFile, as it seems to work so much better and with less dependencies.

**Comment by roymacdonald** [comment]
FYI, I've updated to ofxAudioFile. Not sure if it solves this issue. Haven't tested it.
