### ISSUE TITLE
Request: Example with multichannel player

### ISSUE THREAD

**Issue by gomesgustavo** [roymacdonald/ofxSoundObjects#28]
Hi,

Firstly, thanks for this amazing addon!

I am trying to figure out how can I control the output channel from a single file, and I believe this kind of manipulation is done only when using the ofxSoundMatrixMixer, is it right?

I am trying to create a single audio player where I can choose a specific channel to output.
Can you help me please?

Cheers!

**Comment by roymacdonald** [comment]
Hi gustavo, 
thanks for the kind words.
you can do so with the matrix mixer, although if you just want to route it to a specific channel it is more efficient to use the multiplexer. I just added an example, "example-soundPlayerMultiOutput", Check it and let me know how it goes.

cheers

**Comment by gomesgustavo** [comment]
That is perfect! Thank you very much @roymacdonald!

**Comment by roymacdonald** [comment]
no problem. :)
