### ISSUE TITLE
Audio input-only fails silently

### ISSUE THREAD

**Issue by Autr** [roymacdonald/ofxSoundObjects#30]
Hi there, on a setup like so:

```
    stream.setup(2, 2, 44100, 256, 1);
    stream.setInput(input);
    stream.setOutput(output);
    input.connectTo( visualizer ).connectTo(output);
```

I found that if either `connectTo(output)` or `stream.setOutput(output) ` are removed, or if the ofSoundStream output channels are set to 0, then the entire chain doesn't run.  Perhaps an ofLogWarning / ofLogError?

**Comment by roymacdonald** [comment]
Hi, 
This is intended to be as such.
The whole chain system runs using a pull through method, which means that the output will pull the data throught all the different chained objects. So if you remove it there is none that will do such.
I have another branch that supports having an input alone, with no output.

It is not possible to have a warning currently as it mostly implies having a way to detect how everything is connected and then determining if it needs an input or not.

Thanks for your suggestion anyways

**Comment by Autr** [comment]
Ah thanks for the explainer Roy, it makes perfect sense. I’m interested to read more about events chaining techniques if you have recommendations. I’m making something involving OSC nodes: so my current approach would be to sort them by distance from an eventual output node, and recursively update them in order of depth. The idea I’m stuck at is if two chains (being draw by their output node) are connected together. I could recursively update each chain depth in relation to each other, but it feels like infinite loop territory.

**Comment by roymacdonald** [comment]
Hi @Autr .
I would think that this is called [graph theory](https://en.wikipedia.org/wiki/Graph_theory) and you might want to take a look to the [Traveling Salesman Problem](https://github.com/elliotwoods/ofxTSP). Besides this I work mostly out of intuition and logic, so I don't really have a more technical details about it.
best
