### ISSUE TITLE
Devices are not being recognized on Windows

### ISSUE THREAD

**Issue by GutoPereira** [roymacdonald/ofxSoundObjects#47]
Hi Roy,

I am trying to reproduce a audio file to the headphones(Green) and the HDMI(yellow) on a Windows 11 with of0.11.2.

![image](https://user-images.githubusercontent.com/24294885/194145703-2ebebc60-7341-480b-82d7-c9d8e13cb2da.png)

But the ofxSoundObject is not recognizing these devices.

When doing ``ofxSoundUtils::printOutputSoundDevices();`` it prints nothing.

When doing ``cout << ofxSoundUtils::getOutputSoundDevices() << endl;``  it prints:
```
[Unkown API: 0] ASIO4ALL v2 [in:2 out:2] (default in) (default out)
[Unkown API: 1] Realtek ASIO [in:2 out:2]
```

And when doing ``stream.printDeviceList();`` it prints:
```
RtAudio: no compiled support for specified API argument!

RtAudio: no compiled support for specified API argument!

RtAudio: no compiled support for specified API argument!

RtAudio: no compiled support for specified API argument!

RtAudio: no compiled support for specified API argument!
```

Could you please help?

Cheers,
Guto

**Comment by GutoPereira** [comment]
Thank you, it shows the missing devices.
How can I set one of them to be the output?

Because the given example uses another method that does not contain the desired device:
```
auto outDevices = ofxSoundUtils::getOutputSoundDevices();

cout << outDevices << endl;
settings.setOutDevice(outDevices[outDeviceIndex]);
```

``outDevices`` only shows:
```
[Unkown API: 0] ASIO4ALL v2 [in:2 out:2] (default in) (default out)
[Unkown API: 1] Realtek ASIO [in:2 out:2]
```

I've tried to set it in the settings, but had no effect:
```
settings.setApi(ofSoundDevice::Api::MS_WASAPI);
```

Thank you once again!

**Comment by GutoPereira** [comment]
Found it!!

```
settings.setApi(ofSoundDevice::Api::MS_DS);

size_t outDeviceIndex = 2;
std::vector<ofSoundDevice> devices = stream.getDeviceList(ofSoundDevice::Api::MS_DS);
settings.setOutDevice(devices[outDeviceIndex]);
cout << devices << endl;
```

Thank you for the amazing addon!

**Comment by roymacdonald** [comment]
glad you found it. 
cheers.
