### ISSUE TITLE
ofxMultiSoundPlayer::getCurrentBuffer() not implemented

### ISSUE THREAD

**Issue by virusys** [roymacdonald/ofxSoundObjects#48]
It's declared on line 64 of `ofxMultiSoundPlayer.h` but not defined:

```const ofSoundBuffer & getCurrentBuffer() const;```

**Comment by roymacdonald** [comment]
Hi, 
I just removed that function. I shouldn't have been there in first place.
cheers

**Comment by virusys** [comment]
Cool, great addon by the way!
