### ISSUE TITLE
qtcreator libmpg123 

### ISSUE THREAD

**Issue by thomasgeissl** [roymacdonald/ofxSoundObjects#5]
Do we use libmpg123 on osx?
The qt creator wizzard defines OF_USING_MPG123 which leads to a file not found error.
I guess this issue should be reported in the of repo.

https://github.com/openframeworks/openFrameworks/blob/035af4555da07ec7cd332cec4ee75af9e1bffdda/libs/openFrameworksCompiled/project/qtcreator/modules/of/of.qbs#L398

https://github.com/roymacdonald/ofxSoundObjects/blob/master/src/ofxSoundFile.h#L22

**Comment by roymacdonald** [comment]
I cant remember correctly but I think that now we don't. I'll check and let you know.
Thanks for posting all this issues.
best!

**Comment by thomasgeissl** [comment]
This is fixed in oF now.

**Comment by roymacdonald** [comment]
great! thanks.
take care
