### ISSUE TITLE
Player is not registering the end event

### ISSUE THREAD

**Issue by bitSpaz** [roymacdonald/ofxSoundObjects#51]
When I run the example-soundPlayerObject everything works great except for "player ended".

I opened the example-soundPlayerObject.
Change player.setLoop() to false.
Run the program.
The expected result is that "the player's instance " << id << "finished playing" prints to the console. It doesn't, however.

Any thoughts on how to resolve this would be most appreciated.

Thanks

macOS 13.13.1
of_v20230712_osx_release

**Comment by roymacdonald** [comment]
Hi. It is a bug. Thanks for pointing out. I will check it.

**Comment by roymacdonald** [comment]
Hi @bitSpaz  I just fixed it.
