### ISSUE TITLE
matrix mixer set cross level to zero by default

### ISSUE THREAD

**Issue by stephanschulz** [roymacdonald/ofxSoundObjects#52]
not sure if it is something I am not doing correctly but trying to see all cross levels to zero towards the end of my setup() function does not right away take effect.
I think it takes a while for `mixer.getNumOutputChannels()` to not be 0.
This results in all levels being 1 by default and if I do not do ` mixer.setMasterVolume(0);` I get a super loud noise until during update() `setAllPlayersCrossPoints(0)` starts working.

```
void setAllPlayersCrossPoints(float _level){
        if(bDebug) ofLog()<<"setAllPlayersCrossPoints() outChannels "<<outChannels<<" , "<<mixer.getNumOutputChannels()<<" to "<<_level;
        if(mixer.getNumOutputChannels() > 0){
            for(int in = 0; in <players.size(); in++ ){
                for(int out = 0; out <outChannels; out++ ){
                    mixer.setVolumeForChannel(_level, in, out);
                }
            }
        }
    }
```

**Comment by roymacdonald** [comment]
Hi, that is done correctly but as the audio stream takes a bit more than the setup to end,  you get such type of issue. I will implement an event which can be registered to. I'll let you know

**Comment by roymacdonald** [comment]
@stephanschulz 
So there was already a solution to this.
`mixer.setOutputVolumeForAllChannels(0);`
where mixer is an instance of  `ofxSoundMatrixMixer`
