### ISSUE TITLE
Files in src/SoundObjects are not added to the header search paths

### ISSUE THREAD

**Issue by thomasgeissl** [roymacdonald/ofxSoundObjects#6]
The files in src/SoundObjects are not found. I get the following error message.
```sh
/Users/thomasgeissl/programming/of/openFrameworks/addons/ofxSoundObjects/example-soundPlayerObject/src/ofApp.h:5:10: fatal error: 'waveformDraw.h' file not found
#include "waveformDraw.h"
```
Should not they be added automatically to the header search paths?

**Comment by thomasgeissl** [comment]
This works now. I do not know why this did not before. I cannot reproduce this.

**Comment by roymacdonald** [comment]
@thomasgeissl all those files in src/SoundObjects should be added on demand, as these are not needed to make the addon work.
